### ISSUE TITLE
Configuration and use problems

### ISSUE THREAD

**Issue by blinkfox** [remkop/jansi-substratevm#2]
Hello, I am using `quarkus` + `picocli` to build a cli program, thank you for providing such a good tool. Now I have also encountered the problem of no ANSI color under Windows.

I introduced `jansi-2.2.0` and `picocli-jansi-graalvm-1.2.0`, then generated and configured `jni-config.json` and `resources-config.json`, but when build a native image under Windows, always throw the exception: `Method org.fusesource.jansi.internal.CLibrary.access$000() not found.`.

Cloud you tell me if there is a problem with my way of use? The exception log as follows:

```bash
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] C:\graalvm-java11\bin\native-image.cmd -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Duser.language=zh -J-Dfile.encoding=UTF-8 -H:JNIConfigurationFiles=jni-config.json -H:ResourceConfigurationFiles=resources-config.json --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar minpack-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:-UseServiceLoaderFeature -H:+StackTrace minpack-runner
[minpack-runner:12712]    classlist:   2,100.82 ms,  0.96 GB
[minpack-runner:12712]        setup:     264.12 ms,  0.96 GB
Error: Error parsing JNI configuration in jar:file:/D:/code/cdpt/effect/packit/minpack/target/minpack-native-image-source-jar/minpack-runner.jar!/META-INF/native-image/picocli-jansi-graalvm/jni-config.json:
Method org.fusesource.jansi.internal.CLibrary.access$000() not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationResources.
com.oracle.svm.core.util.UserError$UserException: Error parsing JNI configuration in jar:file:/D:/code/cdpt/effect/packit/minpack/target/minpack-native-image-source-jar/minpack-runner.jar!/META-INF/native-image/picocli-jansi-graalvm/jni-config.json:
Method org.fusesource.jansi.internal.CLibrary.access$000() not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationResources.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:138)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$3(ConfigurationParserUtils.java:119)
        at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils$1.tryAdvance(ConfigurationParserUtils.java:108)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:491)
        at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:449)
        at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:125)
        at com.oracle.svm.jni.access.JNIAccessFeature.afterRegistration(JNIAccessFeature.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:849)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:849)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.209 s
[INFO] Finished at: 2021-02-05T13:24:59+08:00
[INFO] ------------------------------------------------------------------------
```

Some environmental information:

- Windows 10
- GraalVM 21
- Java 11
- `quarkus`: 1.10.0
- `picocli`: 4.6.1
- `jansi`: 2.2.0
- `picocli-jansi-graalvm`: 1.2.0

**Comment by remkop** [comment]
Hi @blinkfox, thank you for reporting this.

## picocli-jansi-graalvm no longer needed with Jansi 2.2.x?

picocli-jansi-graalvm-1.2.0 was developed as a workaround for issues with Jansi 1.18.
These issues hopefully no longer exist with Jansi 2.2.0 and later (although I have not tested this).

## Native image error 

Looking at the error message:

> Error: Error parsing JNI configuration in jar:file:/D:/code/cdpt/effect/packit/minpack/target/minpack-native-image-source-jar/minpack-runner.jar!/META-INF/native-image/picocli-jansi-graalvm/jni-config.json:
Method org.fusesource.jansi.internal.CLibrary.access$000() not found

I suspect that the API for the `CLibrary` class in Jansi 2.2.0 has changed, and the  `/META-INF/native-image/picocli-jansi-graalvm/jni-config.json` file that is included in `picocli-jansi-graalvm-1.2.0.jar` is no longer valid.

## Solution

Can you try with `jansi-2.1.1.jar` and _without_ picocli-jansi-graalvm-1.2.0? 
It looks like jansi-2.1.1.jar contains its own  `jni-config.json` and `resources-config.json`, so you should not need to generate these files.

Please let me know your results. If this works correctly I will update the project README that `picocli-jansi-graalvm` is incompatible and no longer needed with `jansi-2.1.1`.

**Comment by blinkfox** [comment]
@remkop Thank you for your reply.

I removed `picocli-jansi-graalvm`, and modified the jansi version to `2.1.1`, and did not configure the `resources-config.json` and `jni-config.json` files. The native image can be built , But the built package does not have ANSI Color, which means that `jansi` does not work.

Other versions of jansi also have this problem.

**Comment by remkop** [comment]
@blinkfox Understood, thank you for trying.

Would you mind opening a ticket in the Jansi project to ask them to investigate?
It may be good to have a minimal project that only uses Jansi without anything else (so no Quarkus or picocli is best) to help the Jansi maintainers reproduce the issue.

**Comment by blinkfox** [comment]
Okay thank you.

Finally I wrote a small sample project [picocli-test](https://github.com/blinkfox/picocli-test), if you have time, Cloud you help me see if it is caused by my wrong way of using it.

**Comment by remkop** [comment]
@blinkfox Looking at the source code, it seems fine.

You said the application does not show ANSI colors, is this only a problem for native images?
Or are ANSI colors also not showing when running `EntryCommand` as a normal Java application on the JVM?

**Comment by blinkfox** [comment]
@remkop Yes, ANSI colors cannot be displayed only under Windows native image.

I wrote a sample project [ansi-demo](https://github.com/blinkfox/picocli-test/tree/master/ansi-demo) with only `jansi`, which can print ANSI colors normally under JVM and native image.

I should try again using only `picocli` and `jansi`.

**Comment by remkop** [comment]
> I wrote a sample project ansi-demo with only jansi, which can print ANSI colors normally under JVM and native image.

Oh good! We are zooming in to the cause of the issue! :-)

I would advise to call `AnsiConsole.systemInstall()`  as early as possible in the application.
In a `picocli`-only app, I would do this in the `main` method of the app class.

In a Quarkus app, perhaps the [`run` method of a `@QuarkusMain`-annotated class that extends `QuarkusApplication`](https://quarkus.io/guides/picocli#providing-own-quarkusmain) is the best place to call `AnsiConsole.systemInstall()`, I am not sure... (See also the Quarkus [command mode](https://quarkus.io/guides/command-mode-reference) reference guide.)

**Comment by blinkfox** [comment]
I tried using only `picocli` and `jansi`, here is [picocli-jansi](https://github.com/blinkfox/picocli-test/tree/master/picocli-jansi) demo, and there is no problem.

It seems that I really need to use `QuarkusMain` to test.

**Comment by blinkfox** [comment]
The `QuarkusMain` way still doesn't work. At present, it should be caused by some factors in Quarkus.

**Comment by remkop** [comment]
Interesting! I wasn’t aware of this. Perhaps the ticket should be raised with Quarkus. Can you do that?

**Comment by blinkfox** [comment]
I will, thank you for your help

**Comment by remkop** [comment]
No worries!
Let me know how it goes!
